In [ ]:
import os
from dotenv import load_dotenv
from sqlalchemy import create_engine
from sqlalchemy.engine import URL

load_dotenv()  # reads variables from a local .env file (not committed to git)

url = URL.create(
    "mysql+pymysql",
    username=os.getenv("DB_USER", "root"),
    password=os.getenv("DB_PASSWORD"),
    host=os.getenv("DB_HOST", "localhost"),
    port=int(os.getenv("DB_PORT", "3306")),
)

engine = create_engine(url)

with engine.connect() as conn:
    print("MariaDB connected successfully!")

In [ ]:
import os
from dotenv import load_dotenv
from sqlalchemy import create_engine
from sqlalchemy.engine import URL

load_dotenv()  # reads variables from a local .env file (not committed to git)

url = URL.create(
    "mysql+pymysql",
    username=os.getenv("DB_USER", "root"),
    password=os.getenv("DB_PASSWORD"),
    host=os.getenv("DB_HOST", "localhost"),
    port=int(os.getenv("DB_PORT", "3306")),
)

engine = create_engine(url)

with engine.connect() as conn:
    print("MariaDB connected successfully!")

In [ ]:
import os
from dotenv import load_dotenv
from sqlalchemy import create_engine
from sqlalchemy.engine import URL

load_dotenv()  # reads variables from a local .env file (not committed to git)

url = URL.create(
    "mysql+pymysql",
    username=os.getenv("DB_USER", "root"),
    password=os.getenv("DB_PASSWORD"),
    host=os.getenv("DB_HOST", "localhost"),
    port=int(os.getenv("DB_PORT", "3306")),
)

engine = create_engine(url)

with engine.connect() as conn:
    print("MariaDB connected successfully!")

In [ ]:
import os
from dotenv import load_dotenv
from sqlalchemy import create_engine
from sqlalchemy.engine import URL

load_dotenv()  # reads variables from a local .env file (not committed to git)

url = URL.create(
    "mysql+pymysql",
    username=os.getenv("DB_USER", "root"),
    password=os.getenv("DB_PASSWORD"),
    host=os.getenv("DB_HOST", "localhost"),
    port=int(os.getenv("DB_PORT", "3306")),
)

engine = create_engine(url)

with engine.connect() as conn:
    print("MariaDB connected successfully!")

In [33]:
%pip install sqlalchemy pymysql

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: sqlalchemy in c:\users\user\appdata\roaming\python\python312\site-packages (2.0.50)
Requirement already satisfied: pymysql in c:\users\user\appdata\roaming\python\python312\site-packages (1.2.0)
Requirement already satisfied: greenlet>=1 in c:\users\user\appdata\roaming\python\python312\site-packages (from sqlalchemy) (3.3.1)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\user\appdata\roaming\python\python312\site-packages (from sqlalchemy) (4.15.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [34]:
from sqlalchemy import text

with engine.connect() as conn:
    conn.execute(text("CREATE DATABASE IF NOT EXISTS ecommerce"))
    conn.commit()

print("ecommerce database created successfully!")

ecommerce database created successfully!

In [ ]:
import os
from sqlalchemy import create_engine
from sqlalchemy.engine import URL

url = URL.create(
    "mysql+pymysql",
    username=os.getenv("DB_USER", "root"),
    password=os.getenv("DB_PASSWORD"),
    host=os.getenv("DB_HOST", "localhost"),
    port=int(os.getenv("DB_PORT", "3306")),
    database="ecommerce",
)

engine = create_engine(url)

print("Connected to ecommerce!")

In [36]:
import pandas as pd

df = pd.read_csv("Clean_Ecommerce.csv")

print("Rows:", len(df))
print("Columns:", len(df.columns))

df.head()

Rows: 358
Columns: 21

,Order_ID,Order_Date,Customer_Name,Email,Phone,City,State,Product,Category,Qty,...,Discount,Payment_Mode,Order_Status,Delivery_Date,Sales,Net_Amount,Profit,Month,Year,Weekday
0,ORD1002,30-06-2025,Neha,neha82@gmail.com,9.829008e+09,Delhi,Delhi,Chair,Furniture,4.0,...,NaN,UPI,Pending,03-07-2025,7996.0,7996.00,1599.20,June,2025,Monday
1,ORD1003,03-02-2025,Rohit,rohit45@gmail.com,9.280491e+09,Pune,Maharashtra,Watch,Fashion,5.0,...,20.0,Card,Pending,09-02-2025,24995.0,19996.00,3999.20,February,2025,Monday
2,ORD1004,06-05-2025,Amit,amit6@gmail.com,9.943311e+09,Jaipur,Rajasthan,Mouse,Electronics,3.0,...,5.0,COD,Returned,08-05-2025,5997.0,5697.15,1139.43,May,2025,Tuesday
3,ORD1007,10-02-2025,Rahul,rahul82@gmail.com,9.517780e+09,Mumbai,Maharashtra,Mouse,Electronics,3.0,...,20.0,Wallet,Cancelled,18-02-2025,1497.0,1197.60,239.52,February,2025,Monday
4,ORD1008,17-02-2025,Rahul,rahul71@gmail.com,9.789375e+09,Lucknow,UP,Mouse,Electronics,4.0,...,NaN,Card,Returned,27-02-2025,39996.0,39996.00,7999.20,February,2025,Monday

In [37]:
df.to_sql(
    "ecommerce_data",
    con=engine,
    if_exists="replace",
    index=False
)

print("Data loaded successfully!")

Data loaded successfully!

In [ ]:
# Connection string now built from environment variables (see cells above) instead of being hardcoded here.

In [ ]:
# Connection string now built from environment variables (see cells above) instead of being hardcoded here.

In [ ]:
import os
from sqlalchemy import create_engine
from urllib.parse import quote_plus

password = quote_plus(os.getenv("DB_PASSWORD", ""))

engine = create_engine(
    f"mysql+pymysql://{os.getenv('DB_USER','root')}:{password}@{os.getenv('DB_HOST','localhost')}/ecommerce"
)

print("MariaDB connected successfully!")

In [41]:
pd.read_sql("SHOW TABLES", engine)

  Tables_in_ecommerce
0      ecommerce_data

In [42]:
pd.read_sql("SHOW DATABASES", engine)

             Database
0           ecommerce
1  information_schema
2               mysql
3                 new
4  performance_schema
5          phpmyadmin
6          startersql
7                test

In [43]:
pd.read_sql("SELECT DATABASE()", engine)

  DATABASE()
0  ecommerce

In [44]:
import pandas as pd

df = pd.read_excel("Ecommerce_Unclean_Project.xlsx")

print("Data loaded successfully!")

Data loaded successfully!

In [45]:
df.shape

(545, 15)

In [46]:
pd.read_sql("SELECT COUNT(*) AS total_rows FROM ecommerce_data", engine)

   total_rows
0         358

In [47]:
pd.read_sql("DESCRIBE ecommerce_data", engine)

            Field        Type Null Key Default Extra
0        Order_ID        text  YES        None
1      Order_Date        text  YES        None
2   Customer_Name        text  YES        None
3           Email        text  YES        None
4           Phone      double  YES        None
5            City        text  YES        None
6           State        text  YES        None
7         Product        text  YES        None
8        Category        text  YES        None
9             Qty      double  YES        None
10     Unit_Price      double  YES        None
11       Discount      double  YES        None
12   Payment_Mode        text  YES        None
13   Order_Status        text  YES        None
14  Delivery_Date        text  YES        None
15          Sales      double  YES        None
16     Net_Amount      double  YES        None
17         Profit      double  YES        None
18          Month        text  YES        None
19           Year  bigint(20)  YES        None
20        Weekday        text  YES        None

In [48]:
pd.read_sql("SELECT COUNT(*) AS total_rows FROM ecommerce_data", engine)

   total_rows
0         358

In [49]:
result = pd.read_sql(
    "SELECT COUNT(*) AS total_rows FROM ecommerce_data",
    engine
)

print(result.to_string(index=False))

 total_rows
        358

In [50]:
data = pd.read_sql(
    "SELECT * FROM ecommerce_data LIMIT 5",
    engine
)

data

,Order_ID,Order_Date,Customer_Name,Email,Phone,City,State,Product,Category,Qty,...,Discount,Payment_Mode,Order_Status,Delivery_Date,Sales,Net_Amount,Profit,Month,Year,Weekday
0,ORD1002,30-06-2025,Neha,neha82@gmail.com,9.829008e+09,Delhi,Delhi,Chair,Furniture,4.0,...,NaN,UPI,Pending,03-07-2025,7996.0,7996.00,1599.20,June,2025,Monday
1,ORD1003,03-02-2025,Rohit,rohit45@gmail.com,9.280491e+09,Pune,Maharashtra,Watch,Fashion,5.0,...,20.0,Card,Pending,09-02-2025,24995.0,19996.00,3999.20,February,2025,Monday
2,ORD1004,06-05-2025,Amit,amit6@gmail.com,9.943311e+09,Jaipur,Rajasthan,Mouse,Electronics,3.0,...,5.0,COD,Returned,08-05-2025,5997.0,5697.15,1139.43,May,2025,Tuesday
3,ORD1007,10-02-2025,Rahul,rahul82@gmail.com,9.517780e+09,Mumbai,Maharashtra,Mouse,Electronics,3.0,...,20.0,Wallet,Cancelled,18-02-2025,1497.0,1197.60,239.52,February,2025,Monday
4,ORD1008,17-02-2025,Rahul,rahul71@gmail.com,9.789375e+09,Lucknow,UP,Mouse,Electronics,4.0,...,NaN,Card,Returned,27-02-2025,39996.0,39996.00,7999.20,February,2025,Monday

In [51]:
result = pd.read_sql(
    "SELECT COUNT(*) AS total_rows FROM ecommerce_data",
    engine
)

print(result)

   total_rows
0         358

In [52]:
data = pd.read_sql(
    "SELECT * FROM ecommerce_data LIMIT 5",
    engine
)

data

,Order_ID,Order_Date,Customer_Name,Email,Phone,City,State,Product,Category,Qty,...,Discount,Payment_Mode,Order_Status,Delivery_Date,Sales,Net_Amount,Profit,Month,Year,Weekday
0,ORD1002,30-06-2025,Neha,neha82@gmail.com,9.829008e+09,Delhi,Delhi,Chair,Furniture,4.0,...,NaN,UPI,Pending,03-07-2025,7996.0,7996.00,1599.20,June,2025,Monday
1,ORD1003,03-02-2025,Rohit,rohit45@gmail.com,9.280491e+09,Pune,Maharashtra,Watch,Fashion,5.0,...,20.0,Card,Pending,09-02-2025,24995.0,19996.00,3999.20,February,2025,Monday
2,ORD1004,06-05-2025,Amit,amit6@gmail.com,9.943311e+09,Jaipur,Rajasthan,Mouse,Electronics,3.0,...,5.0,COD,Returned,08-05-2025,5997.0,5697.15,1139.43,May,2025,Tuesday
3,ORD1007,10-02-2025,Rahul,rahul82@gmail.com,9.517780e+09,Mumbai,Maharashtra,Mouse,Electronics,3.0,...,20.0,Wallet,Cancelled,18-02-2025,1497.0,1197.60,239.52,February,2025,Monday
4,ORD1008,17-02-2025,Rahul,rahul71@gmail.com,9.789375e+09,Lucknow,UP,Mouse,Electronics,4.0,...,NaN,Card,Returned,27-02-2025,39996.0,39996.00,7999.20,February,2025,Monday

In [53]:
data = pd.read_sql(
    "SELECT * FROM ecommerce_data LIMIT 5",
    engine
)

data

,Order_ID,Order_Date,Customer_Name,Email,Phone,City,State,Product,Category,Qty,...,Discount,Payment_Mode,Order_Status,Delivery_Date,Sales,Net_Amount,Profit,Month,Year,Weekday
0,ORD1002,30-06-2025,Neha,neha82@gmail.com,9.829008e+09,Delhi,Delhi,Chair,Furniture,4.0,...,NaN,UPI,Pending,03-07-2025,7996.0,7996.00,1599.20,June,2025,Monday
1,ORD1003,03-02-2025,Rohit,rohit45@gmail.com,9.280491e+09,Pune,Maharashtra,Watch,Fashion,5.0,...,20.0,Card,Pending,09-02-2025,24995.0,19996.00,3999.20,February,2025,Monday
2,ORD1004,06-05-2025,Amit,amit6@gmail.com,9.943311e+09,Jaipur,Rajasthan,Mouse,Electronics,3.0,...,5.0,COD,Returned,08-05-2025,5997.0,5697.15,1139.43,May,2025,Tuesday
3,ORD1007,10-02-2025,Rahul,rahul82@gmail.com,9.517780e+09,Mumbai,Maharashtra,Mouse,Electronics,3.0,...,20.0,Wallet,Cancelled,18-02-2025,1497.0,1197.60,239.52,February,2025,Monday
4,ORD1008,17-02-2025,Rahul,rahul71@gmail.com,9.789375e+09,Lucknow,UP,Mouse,Electronics,4.0,...,NaN,Card,Returned,27-02-2025,39996.0,39996.00,7999.20,February,2025,Monday

In [54]:
pd.read_sql("DESCRIBE ecommerce_data", engine)

            Field        Type Null Key Default Extra
0        Order_ID        text  YES        None
1      Order_Date        text  YES        None
2   Customer_Name        text  YES        None
3           Email        text  YES        None
4           Phone      double  YES        None
5            City        text  YES        None
6           State        text  YES        None
7         Product        text  YES        None
8        Category        text  YES        None
9             Qty      double  YES        None
10     Unit_Price      double  YES        None
11       Discount      double  YES        None
12   Payment_Mode        text  YES        None
13   Order_Status        text  YES        None
14  Delivery_Date        text  YES        None
15          Sales      double  YES        None
16     Net_Amount      double  YES        None
17         Profit      double  YES        None
18          Month        text  YES        None
19           Year  bigint(20)  YES        None
20        Weekday        text  YES        None

In [55]:
# ===== CLEAN THE UNCLEAN EXCEL FILE (fixed pipeline) =====
import pandas as pd
import numpy as np

# 1. Always re-read the unclean file fresh (this picks up any rows you just added)
df = pd.read_excel("Ecommerce_Unclean_Project.xlsx")
print("Rows loaded from unclean file:", len(df))

# 2. Clean column names
df.columns = df.columns.str.strip()

# 3. Strip whitespace from all text columns, normalize blank-like values to NaN
for col in df.select_dtypes(include="object").columns:
    df[col] = df[col].astype(str).str.strip()
    df[col] = df[col].replace({"nan": np.nan, "": np.nan, "None": np.nan, "NaT": np.nan})

# 4. Drop fully duplicate rows
df = df.drop_duplicates()

# 5. Drop duplicate Order_ID, keep the first occurrence
if "Order_ID" in df.columns:
    df = df.drop_duplicates(subset="Order_ID", keep="first")

# 6. Drop rows missing an essential identifier
essential_cols = [c for c in ["Order_ID", "Order_Date"] if c in df.columns]
if essential_cols:
    df = df.dropna(subset=essential_cols)

# 7. Parse dates (dayfirst since your data uses dd-mm-yyyy)
for date_col in ["Order_Date", "Delivery_Date"]:
    if date_col in df.columns:
        df[date_col] = pd.to_datetime(df[date_col], errors="coerce", dayfirst=True)

if "Order_Date" in df.columns:
    df = df.dropna(subset=["Order_Date"])

# 8. Numeric cleanup
for num_col in ["Qty", "Unit_Price", "Discount"]:
    if num_col in df.columns:
        df[num_col] = pd.to_numeric(df[num_col], errors="coerce")

needed_numeric = [c for c in ["Qty", "Unit_Price"] if c in df.columns]
if needed_numeric:
    df = df.dropna(subset=needed_numeric)

# 9. Derive Sales / Net_Amount / Profit if the unclean file doesn't already have them
if "Sales" not in df.columns and {"Qty", "Unit_Price"}.issubset(df.columns):
    df["Sales"] = df["Qty"] * df["Unit_Price"]

if "Net_Amount" not in df.columns and {"Sales", "Discount"}.issubset(df.columns):
    df["Net_Amount"] = df["Sales"] * (1 - df["Discount"].fillna(0) / 100)

# NOTE: 20% is a PLACEHOLDER profit margin — replace with your real profit formula/column
if "Profit" not in df.columns and "Net_Amount" in df.columns:
    df["Profit"] = df["Net_Amount"] * 0.20

# 10. Derive Month / Year / Weekday from Order_Date, then format dates back to dd-mm-yyyy strings
if "Order_Date" in df.columns:
    df["Month"] = df["Order_Date"].dt.month_name()
    df["Year"] = df["Order_Date"].dt.year
    df["Weekday"] = df["Order_Date"].dt.day_name()
    df["Order_Date"] = df["Order_Date"].dt.strftime("%d-%m-%Y")
    if "Delivery_Date" in df.columns:
        df["Delivery_Date"] = df["Delivery_Date"].dt.strftime("%d-%m-%Y")

print("Rows after cleaning:", len(df))
print("Columns:", list(df.columns))
df.head()

Rows loaded from unclean file: 545
Rows after cleaning: 358
Columns: ['Order_ID', 'Order_Date', 'Customer_Name', 'Email', 'Phone', 'City', 'State', 'Product', 'Category', 'Qty', 'Unit_Price', 'Discount', 'Payment_Mode', 'Order_Status', 'Delivery_Date', 'Sales', 'Net_Amount', 'Profit', 'Month', 'Year', 'Weekday']

C:\Users\USER\AppData\Local\Temp\ipykernel_8424\1134780500.py:13: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for col in df.select_dtypes(include="object").columns:

,Order_ID,Order_Date,Customer_Name,Email,Phone,City,State,Product,Category,Qty,...,Discount,Payment_Mode,Order_Status,Delivery_Date,Sales,Net_Amount,Profit,Month,Year,Weekday
0,ORD1002,30-06-2025,Neha,neha82@gmail.com,9.829008e+09,Delhi,Delhi,Chair,Furniture,4.0,...,NaN,UPI,Pending,03-07-2025,7996.0,7996.00,1599.20,June,2025,Monday
1,ORD1003,03-02-2025,Rohit,rohit45@gmail.com,9.280491e+09,Pune,Maharashtra,Watch,Fashion,5.0,...,20.0,Card,Pending,09-02-2025,24995.0,19996.00,3999.20,February,2025,Monday
2,ORD1004,06-05-2025,Amit,amit6@gmail.com,9.943311e+09,Jaipur,Rajasthan,Mouse,Electronics,3.0,...,5.0,COD,Returned,08-05-2025,5997.0,5697.15,1139.43,May,2025,Tuesday
5,ORD1007,10-02-2025,Rahul,rahul82@gmail.com,9.517780e+09,Mumbai,Maharashtra,Mouse,Electronics,3.0,...,20.0,Wallet,Cancelled,18-02-2025,1497.0,1197.60,239.52,February,2025,Monday
6,ORD1008,17-02-2025,Rahul,rahul71@gmail.com,9.789375e+09,Lucknow,UP,Mouse,Electronics,4.0,...,NaN,Card,Returned,27-02-2025,39996.0,39996.00,7999.20,February,2025,Monday

In [56]:
# ===== PUSH CLEANED DATA TO THE SQL TABLE POWER BI READS FROM =====
# This is the step that was MISSING before — without it, Power BI never sees your new rows.

# Save a clean CSV too (optional, in case you ever want to point Power BI at the file directly)
df.to_csv("Clean_Ecommerce.csv", index=False)

df.to_sql(
    "ecommerce_data",
    con=engine,
    if_exists="replace",
    index=False
)

print("Cleaned data pushed to SQL. Rows now in ecommerce_data table:", len(df))

Cleaned data pushed to SQL. Rows now in ecommerce_data table: 358